FROM golang:1.24-alpine AS build
WORKDIR /src
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN go mod tidy && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o /out/sender ./cmd/sender

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/sender /sender
USER nonroot:nonroot
EXPOSE 9999
ENTRYPOINT ["/sender"]
